config/routes.rb
Rails.application.routes.draw do

  root 'first#index'

  get 'second' => 'second#index', as: :second
  get 'third' => 'third#index', as: :third
  get 'fourth' => 'fourth#index', as: :fourth

  get 'sixth' => 'sixth#index', as: :sixth
  


end

app/models/second.rb
class Second < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fifth_controller.rb
class FifthController < ApplicationController
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
end

app/controllers/fourth_controller.rb
class FourthController < ApplicationController
end

app/controllers/second_controller.rb
class SecondController < ApplicationController

  def index
    @ficelle = Second.all
  end
end

app/controllers/sixth_controller.rb
class SixthController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fifth_helper.rb
module FifthHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/fourth_helper.rb
module FourthHelper
end

app/helpers/second_helper.rb
module SecondHelper
end

app/helpers/sixth_helper.rb
module SixthHelper
end

app/helpers/third_helper.rb
module ThirdHelper
end

app/views/fifth/index.haml
%h1 Point de répis dans notre aventure...
%p Sur la dernière marche du chemin de "Search" ne vous contentez pas de répondre bêtement, pensez aussi à faire connaissance avec les subtilités de Rub Ydris... L'une d'entre elles se nomme HAML...
= link_to "Ne vous contentez pas du minimum...", sixth_path

app/views/first/index.haml
%h1 Bravo vous avez réussi les premières étape!
%p Sur le chemin de "Search" vous avez certainement fait connaissance avec Mr El'Goog il est charmant, plein de piment, bien heureusement car il doit devenir votre ami... Tachez donc d'être clair et précis avec lui...
%p PS: Sa pièce de théatre préfèré est Antoine et Cléopâtre...
  = link_to "Etape deux", second_path

app/views/fourth/index.haml
%h1 Félicitation!!
%p Sur le chemin de "Search" en compagnie de nos 4 amis vous apprendrais vite que les routes sont longues...
= link_to "En routes?", fifth_path

app/views/layouts/application.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title= "WildBoard" + yield(:title)
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body(class=controller_name)
    .content
      = yield

app/views/second/index.haml
%h1 La suite?
%p Sur le chemin de "Search" Mr El'Goog ne vous donnera pas toujours ce que vous espériez, il est riche d'années d'expériences et de connaissances mais peut parfois être aussi conpréhenssif qu'un feu rouge...
= link_to "Un feu rouge?", third_path

app/views/third/index.haml
%h1 On avance encore...
%p Sur le chemin de "Search" et notre rencontre avec Mr El'Goog vous en avez appris un peu plus sur Rub Ydris mais Mr El'Goog vous permettra de faire connaissance avec Paul-Henry Pitchpi ou encore Jean Van'Script...
= link_to "Rub Ydris vous réserve encore bien des surprises...", fourth_path